### ISSUE TITLE
Feature Request : Renaming files downloaded in bulk downloads

### ISSUE THREAD

**Issue by salmanulfarzy** [tanaikech/goodls#14]
Option to rename files downloaded via multiple URL file inputs. So while passing list of URL via file like, `goodls < list.csv` would it be possible to provide an option to rename the downloaded files ?

<details>
<summary> Previous description</summary>
I was trying to download bulk files with `goodls` and renaming them by passing information from CSV file. But the `-f` doesn't seem to have any effect. 

If I understand correctly, file input doesn't support file naming. It would be great if you could let me know what I'm missing here. 

```bash
while IFS=, read -r id gdlink; do
   echo "Fetching $gdlink to $id"
   goodls -u "$gdlink" -f "$id"
done < goodls_sample_products.csv
```
Output
```
Fetching //drive.google.com/uc?export=download&id=1HGkFBVuKHx5jokRf5ToH_03UOhVB6ScX to 3911401000000874007
Downloading (bytes)... 80817
{"Filename": "1.jpg", "Type": "file", "MimeType": "image/jpeg", "FileSize": 80817}
Downloading (bytes)... 24986
{"Filename": "LATINE BEIGE.jpg", "Type": "file", "MimeType": "image/jpeg", "FileSize": 24986}
```

Sample data
```csv
3911401000000874007,//drive.google.com/uc?export=download&id=1HGkFBVuKHx5jokRf5ToH_03UOhVB6ScX
3911401000000874003,//drive.google.com/uc?export=download&id=1mKPzSb2_XdERUwcKYkT5DV3FVhvnPWmv
3911401000000872221,//drive.google.com/uc?export=download&id=1pplVG_66kUiAarPo98X8dfy3vCpuO9bS
```
</details>

**Comment by tanaikech** [comment]
Thank you for your comment. Unfortunately, when I tested the following command, I could confirm that no error occurs and the downloaded file has the filename of `sample.csv`.

```bash
$ goodls -f sample.csv -u https://drive.google.com/file/d/{fileId}/view?usp=sharing
```

**Comment by salmanulfarzy** [comment]
This would rename the file as `sample.csv`, right ? I would like to rename them with values in column 1. Excuse me if I'm not understanding this. 

So file in //drive.google.com/uc?export=download&id=1HGkFBVuKHx5jokRf5ToH_03UOhVB6ScX has to be renamed as 3911401000000874007. What happens is, once, first command to fetch file is called, following shell commands are not executed. Tried running command in sub-shell also.

```log
// echo of first file
Fetching //drive.google.com/uc?export=download&id=1HGkFBVuKHx5jokRf5ToH_03UOhVB6ScX to 3911401000000874007
// no execution of echo after this. 
// Only two files are downlaoded. First file was never downloaded.
Downloading (bytes)... 80817
{"Filename": "1.jpg", "Type": "file", "MimeType": "image/jpeg", "FileSize": 80817}
Downloading (bytes)... 24986
{"Filename": "LATINE BEIGE.jpg", "Type": "file", "MimeType": "image/jpeg", "FileSize": 24986}
```

**Comment by tanaikech** [comment]
Thank you for replying. Unfortunately, I cannot replicate your situation. When I tested the following command again, I could confirm that no error occurs and the downloaded file has the filename of `sample.csv` again.

```
$ goodls -f sample.csv -u https://drive.google.com/file/d/{fileId}/view?usp=sharing
```

**Comment by salmanulfarzy** [comment]
Let me try to explain my use case, I have CSV file with `id` and `gdlink` in two columns. I need to download links specified in second column and save it as `id` specified in first column. 

So in following data, I need to save file in location https://drive.google.com/uc?export=download&id=1HGkFBVuKHx5jokRf5ToH_03UOhVB6ScX as `3911401000000874007`. File in location https://drive.google.com/uc?export=download&id=1mKPzSb2_XdERUwcKYkT5DV3FVhvnPWmv as `3911401000000874003` and so forth for about 9500+ rows. 

```csv
3911401000000874007,//drive.google.com/uc?export=download&id=1HGkFBVuKHx5jokRf5ToH_03UOhVB6ScX
3911401000000874003,//drive.google.com/uc?export=download&id=1mKPzSb2_XdERUwcKYkT5DV3FVhvnPWmv
3911401000000872221,//drive.google.com/uc?export=download&id=1pplVG_66kUiAarPo98X8dfy3vCpuO9bS
```

I was trying to iterate through rows with bash and invoke `goodls` for each row. So for each row, `goods` will be called to download file at location `$gdlink` and be saved to local as `$id`. 

```
goodls -u "$gdlink" -f "$id"
```

But the execution get bypassed after processing first row. `echo` in first line of loop was never executed after first file. 

Would it be possible to pass filenames while bulk downloading links ?

Thank you for your patience.

**Comment by tanaikech** [comment]
Thank you for replying. Unfortunately, I cannot understand about your replying. In this application, I could confirm that `$ goodls -f sample.csv -u https://drive.google.com/file/d/{fileId}/view?usp=sharing` could be used. So I cannot understand about `Would it be possible to pass filenames while bulk downloading links ?`. If you are saying about [File with several URLs](https://github.com/tanaikech/goodls#file-with-several-urls), in the current stage, the rename of downloaded files is not implemented yet. I apologize for this.

**Comment by salmanulfarzy** [comment]
Never mind. Is it okay if I keep this open as feature request for renaming downloaded files from several URLs ? Feel free to close this otherwise.

**Comment by tanaikech** [comment]
Thank you for replying. Now I could understand about your goal. Although in the current stage, that is not implemented, I could confirm it as the future request. When I implemented it, I would like to tell here.
