### ISSUE TITLE
Can this download the entire Google Drive Folder?

### ISSUE THREAD

**Issue by gotbletu** [tanaikech/goodls#2]
For example downloading a folder full of pictures. Does not seem to work.

```
$ goodls -u 'https://drive.google.com/drive/folders/0By-NOo-lCyxBREtydWtzR0VvcWc?usp=sharing'
Error: Error: URL is wrong.

$ goodls -u 'https://drive.google.com/open?id=0By-NOo-lCyxBREtydWtzR0VvcWc'
Error: Error: URL is wrong
```

**Comment by tanaikech** [comment]
Thank you for your comment. I'm really sorry for the inconvenience. This app cannot download files using the folder ID. When you want to download files in the folder, please use the URLs for each shared file in the folder.

**Comment by gotbletu** [comment]
Ok i see. Thanks for the quick reply

**Comment by tanaikech** [comment]
When the access token is used for this situation, all files in a folder can be retrieved. But when the access token is not used, I couldn't do it. If I found the method for retrieving files in a folder without using access token, I would like to implement this.

**Comment by tanaikech** [comment]
From version 1.2.0, goodls can download all files in a specific folder. Please check it.

**Comment by gotbletu** [comment]
Thanks finally gave it a try; works good =)

https://www.youtube.com/watch?v=ncYzrwTGaJA

**Comment by tanaikech** [comment]
Thank you so much!
