### ISSUE TITLE
Resuming interrupted downloads?

### ISSUE THREAD

**Issue by geoff-codes** [tanaikech/goodls#3]
First of all, this program is lovely—before finding it whenever I needed to do this, I was always digging around my browser trying to find the right cookies to feed to `curl`, and eventually I'd get it, but it was a massive pain.

Anyway, I'm trying to download some VERY large files from my Google Drive. One is >250GB. I expect it to take several days, unfortunately, as I do not have a very speedy connection. Inevitably, unfortunately, there are brief interruptions in the connection, and goodls has quit when this happens, and when I restart, it starts again from byte 0. Is there no way to resume a download at a certain offset using their APIs?

**Comment by tanaikech** [comment]
Thank you for your comment. You can download such large file with resumable. But in the current stage, unfortunately, the function is not implemented to goodls yet. I'm sorry for this situation. 

But, I remembered that I had created the GAS library for downloading the large file. You can know about the method for downloading such large files. Please check this.

https://github.com/tanaikech/DownloadLargeFilesByUrl

**Comment by tanaikech** [comment]
[The resumable download was implemented at v 1.2.0.](https://github.com/tanaikech/goodls#v120)

**Comment by geoff-codes** [comment]
Thank you so much @tanaikech! You write some excellent code!

**Comment by tanaikech** [comment]
Thank you, too.
