### ISSUE TITLE
Getting 'The requested conversion is not supported'

### ISSUE THREAD

**Issue by avinassh** [tanaikech/goodls#33]
I ran the following command:

```
./goodls -u "https://drive.google.com/drive/folders/example?usp=sharing"

Download files from a folder 'ABC'.
There are 1343 files and 294 folders in the folder.

Starting download.

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "The requested conversion is not supported.",
    "locationType": "parameter",
    "location": "convertTo"
   }
  ],
  "code": 400,
  "message": "The requested conversion is not supported."
 }
}
```

Any idea why it is happening and what can be done?

**Comment by tanaikech** [comment]
Now, updated to v2.0.3 by building with the latest version. Please confirm it. When I tested to download a shared folder using this version, I confirmed that no error occurs and the files under the folder can be correctly downloaded.

**Comment by avinassh** [comment]
@tanaikech thank you for pushing a fix! Right now I don't have any shared folder to test, but since you have confirmed already, we can close the issue. If I find any shared folder, I will report here.

**Comment by tanaikech** [comment]
Thank you for testing it.
