### ISSUE TITLE
download to customized folder?

### ISSUE THREAD

**Issue by mrgransky** [tanaikech/goodls#5]
Hi,

I would like to download a folder from my Google-Drive to another directory than my current directory.

The command `$ ./goodls -u [url/to/folder/Google_Drive] ` starts downloading in my current directory!

Is there any option giving a customized path to new directory?

Cheers,

**Comment by tanaikech** [comment]
Thank you for your comment. Yes. The downloaded files are saved to the current directory. The option for inputting the directory for saving the files had never implemented. So I added this at the version 1.2.3. Could you please confirm it?

https://github.com/tanaikech/goodls#v123
