### ISSUE TITLE
[bug] When downloading from a file with multiple folders they gets folded into each other

### ISSUE THREAD

**Issue by karser** [tanaikech/goodls#6]
When downloading folders from a file with several URLs the next downloaded folder is created inside the last created subfolder.
In other words, the current directory gets shifted and the downloaded folders get folded into each other. 

```
#sample.txt
https://drive.google.com/drive/folders/<PUBLIC FOLDER A>
https://drive.google.com/drive/folders/<PUBLIC FOLDER B>
https://drive.google.com/drive/folders/<PUBLIC FOLDER C>
```

Then run
```
goodls < sample.txt
```

Here is the actual file structure:
```
- PUBLIC FOLDER A
  - Subfolder A1
  - Subfolder A2
    - PUBLIC FOLDER B
      - Subfolder B1
      - Subfolder B2
	    - PUBLIC FOLDER C
```

Expected file structure:
```
- PUBLIC FOLDER A
  - Subfolder A1
  - Subfolder A2
- PUBLIC FOLDER B
  - Subfolder B1
  - Subfolder B2
- PUBLIC FOLDER C
```

**Comment by tanaikech** [comment]
Thank you for your comment. When the folders are downloaded from the following structure with `https://drive.google.com/drive/folders/<PUBLIC FOLDER A>\nhttps://drive.google.com/drive/folders/<PUBLIC FOLDER B>\nhttps://drive.google.com/drive/folders/<PUBLIC FOLDER C>`,

```
- PUBLIC FOLDER A
  - Subfolder A1
  - Subfolder A2
    - PUBLIC FOLDER B
      - Subfolder B1
      - Subfolder B2
	    - PUBLIC FOLDER C
```

The downloaded redults are as follows. Each folder is created including the subfolders in the working directory. You can see 3 directories of `PUBLIC FOLDER A`, `PUBLIC FOLDER B` and `PUBLIC FOLDER C` in the working directory.

1. From `https://drive.google.com/drive/folders/<PUBLIC FOLDER A>`,
```
- PUBLIC FOLDER A
  - Subfolder A1
  - Subfolder A2
    - PUBLIC FOLDER B
      - Subfolder B1
      - Subfolder B2
	    - PUBLIC FOLDER C
```

2. From `https://drive.google.com/drive/folders/<PUBLIC FOLDER B>`,
```
- PUBLIC FOLDER B
  - Subfolder B1
  - Subfolder B2
    - PUBLIC FOLDER C
```

3. From `https://drive.google.com/drive/folders/<PUBLIC FOLDER C>`,
```
- PUBLIC FOLDER C
```

These results are the result I expected. So I thought that I might not understand your comment. Can I ask you about the detail of it?

**Comment by karser** [comment]
Sure, I'll prepare a short reproducer.
