### ISSUE TITLE
Author Unidentified when installing on ubuntu

### ISSUE THREAD

**Issue by AmmarRashed** [tanaikech/goodls#7]
when I use the installation command
`go get -u github.com/tanaikech/goodls`

I get the following error:

`# github.com/tanaikech/goodls
../go/src/github.com/tanaikech/goodls/goodls.go:361:3: a.Author undefined (type *cli.App has no field or method Author)
../go/src/github.com/tanaikech/goodls/goodls.go:362:3: a.Email undefined (type *cli.App has no field or method Email)
../go/src/github.com/tanaikech/goodls/goodls.go:366:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/tanaikech/goodls/goodls.go:370:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/tanaikech/goodls/goodls.go:375:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/tanaikech/goodls/goodls.go:379:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/tanaikech/goodls/goodls.go:383:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/tanaikech/goodls/goodls.go:387:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/tanaikech/goodls/goodls.go:391:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/tanaikech/goodls/goodls.go:395:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in array or slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
../go/src/github.com/tanaikech/goodls/goodls.go:395:15: too many errors`

go version:
`go version go1.13.5 linux/amd64`

Ubuntu version: Ubuntu 16.04.3 LTS

**Comment by tanaikech** [comment]
Thank you for your comment. I could confirm the same error. It was found that the reason of the error is due to the update of [https://github.com/urfave/cli](https://github.com/urfave/cli). It was found that the specification was changed by the update. So I updated the script of goodls. Could you please confirm it? In my environment, I could confirm that after this update of goodls, no error ocurs with `go get -u github.com/tanaikech/goodls`.

**Comment by AmmarRashed** [comment]
Thanks! it works now.
Best,
