### ISSUE TITLE
Download stopped when the having quota exceeded error

### ISSUE THREAD

**Issue by yangwenbo99** [tanaikech/goodls#9]
### Problem

I tried to download a folder from Google Drive, which contains many files. After starting the download, the following error is shown and no file is downloaded. 

```
Download files from a folder '(removed due to privacy)'.
There are 1714 files and 0 folders in the folder.
Starting download.
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "downloadQuotaExceeded",
    "message": "The download quota for this file has been exceeded."
   }
  ],
  "code": 403,
  "message": "The download quota for this file has been exceeded."
 }
}


real	1m23.767s
user	0m0.137s
sys	0m0.016s
```

### Expected result

The download process shall continue, but just skipping this file, because there are many other files to download, or at least, showing which file is having the problem, so that I can manually handle problem.

**Comment by tanaikech** [comment]
Thank you for your comment. Although I'm not sure about your actual situation, when I could replicate your situation and correctly understand the reason of the issue, I would like to consider to implement it. I deeply apologize that I cannot find the reason of your issue soon.

**Comment by DrCas** [comment]
I'd like to add on to this. Some Drive folders are shared to a large amount of people, and when a file is downloaded x amount of time Google blocks you from downloading it again. See [this ](https://support.google.com/drive/thread/2035857?hl=en) for example. Maybe you could add an argument to goodls that makes the tool skip files that return errors?

**Comment by tanaikech** [comment]
New option of `--skiperror` was added for implementing this request at v1.2.6. Please check [this](https://github.com/tanaikech/goodls#v126). The sample command is as follows.

```bash
$ goodls -u https://drive.google.com/drive/folders/###?usp=sharing --skiperror
```
